### ISSUE TITLE
Screen goes black while using seek

### ISSUE THREAD

**Issue by GoogleCodeExporter** [seek-for-android/pool#78] opened 2015-03-26 08:28 UTC
```
What's the problem?
I have developed an android application using seek to communicate with UICC and 
using samsung galaxy s4 for testing purpose. The sereen goes black while in the 
activity where seek is used.

What steps will reproduce the problem?
1. While in the activity where seek is used.
2.
3.

What is the expected output? What do you see instead?
The output should be the screen(layout), I have called to show. But Instead it 
shows black screen.

What version of the product are you using? On what operating system?
Galaxy S4. Android 4.3.

Please provide any additional information below.

```

Original issue reported on code.google.com by `situthe...@gmail.com` on 28 Jan 2014 at 11:19

**Comment by marcobrador** [comment] 2015-07-24 07:49
Closed as not a bug on SEEK. Please use the mailing list for help.

**Closed by marcobrador** 2015-07-24 07:49 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
