### ISSUE TITLE
running linux on android

### ISSUE THREAD

**Issue by dimitrieh** [seek-for-android/pool#96] opened 2016-06-29 19:42 UTC
I was directed here from http://stackoverflow.com/questions/19315168/running-docker-on-android as I was looking for running docker on my nexus5. 

Your wiki speaks of running linux on the nexus one.. anyone here familiar with doing so on nexus 5 or with linux on android devices at all?

desired end result: running docker on an (older) android device (nexus5)

**Comment by marcobrador** [comment] 2016-06-30 08:51
Hi dimitrieh,

Thanks for your contribution. However, I am afraid that the link you are referring to is very old and honestly I don't have a clue whether the statements there hold anymore. I've marked the page as unmaintained so it's clear for future visitors that SEEK for Android team does not take care of such topic anymore.

I will proceed to closing the issue as this is not a bug in the code itself. Instead, if you wish to keep the discussion, I encourage you to post a thread in the mailing list (https://groups.google.com/forum/#!forum/seek-for-android), where hopefully someone will be able to help you.

Best regards,
Marc

**Closed by marcobrador** 2016-06-30 08:51 UTC
